# # Classifiers comparison on texts with naive Bayes assumption

In this session of laboratory we compare two models for categorical data probabilistic modeling: 
1. multivariate Bernoulli 
2. multinomial on a dataset 

We adopt a dataset on Twitter messages labelled with emotions (Joy vs Sadness).

The following program shows the loading of the data from a file.

Data are loaded into a matrix X adopting a sparse matrix representation, in order to save space and time.
Sparse matrix representation (in the csr format) represents in three "parallel" arrays the value of the matrix cells that are different from zero and the indices of those matrix cells.
The arrays are called: 
- data
- row
- col

- data[i] stores the value of the matrix cell #i whose indexes are contained in row[i] and col[i] 
- row[i] stores the index of the row in the matrix of the cell #i, 
- col[i] stores the index of the column of the cell #i.


The data file is in csv format.
Any Twitter message has been preprocessed by a Natural Language pipeline which eliminated stop words and substituted the interesting document elements with an integer identifier.  
The interesting document elements might be words, emoji or emoticons. The elements could be repeated in the same document and are uniquely identified in the documents by the same integer number (named "element_id" in the program). This "element_id" number will be used as the index of the column of the data matrix, for the purposes of storage of data.

Each row of the CSV file reports the content of a document (a Twitter message).It is formed as a list of integer number pairs, followed by a string which is the label of the document ("Joy" or "Sadness").
The first number of the pair is the identifier of a document element (the "element_id"); 
the second number of the pair is the count (frequency) of that element in that document.

The dataset has:

tot_n_docs (or rows in the file) =n_rows=11981

n_features (total number of distinct words in the corpus)=11288



The following program reads the data file and loads in a sparse way the matrix using the scipy.sparse library

In [6]:
from numpy import ndarray, zeros
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from scipy.stats import ttest_ind

In [7]:
class_labels = ["Joy","Sadness"]
n_features=11288 # number of columns in the matrix = number of features (distinct elements in the documents)
n_rows=11981 # number rows of the matrix
n_elements=71474 # number of the existing values in the matrix (not empty, to be loaded in the matrix in a sparse way)

path_training="./"
file_name="joy_sadness6000.txt"

# declare the row and col arrays with the indexes of the matrix cells (non-empty) to be loaded from file
# they are needed because the matrix is sparse, and we load in the matrix only the elements which are present
row=np.empty(n_elements, dtype=int)
col=np.empty(n_elements, dtype=int)
data=np.empty(n_elements, dtype=int)

row_n=0 # number of current row to be read and managed
cur_el=0 # position in the three arrays: row, col and data
twitter_labels=[] # list of class labels (target array) of the documents (twitter) that will be read from the input file
twitter_target=[] # list of 0/1 for class labels
with open(path_training + file_name, "r") as fi:
    for line in fi:
        el_list=line.split(',')  # list of integers read from a row of the file
        l=len(el_list)
        last_el=el_list[l-1] # I grab the last element in the list which is the class label
        class_name=last_el.strip() # eliminate the '\n'
        twitter_labels.append(class_name)
        # twitter_labels contains the labels (Joy/Sadness); twitter_target contains 0/1 for the respective labels
        if class_name==class_labels[0]:
           twitter_target.append(0)
        else:
           twitter_target.append(1)
        i=0 # I start reading all the doc elements from the beginning of the list
        while i<(l - 1):
            element_id=int(el_list[i]) # identifier of the element in the document equivalent to the column index
            element_id=element_id-1 # the index starts from 0 (the read id starts from 1)
            i=i+1
            value_cell=int(el_list[i]) # make access to the following value in the file which is the count of the element in the document 
            i=i+1
            row[cur_el]=row_n # load the data in the three arrays: the first two are the row and col indexes; the last one is the matrix cell value
            col[cur_el]=element_id
            data[cur_el]=value_cell
            cur_el=cur_el+1
        row_n=row_n+1
fi.close()
print("final n_row="+str(row))
# loads the matrix by means of the indexes and the values in the three arrays just filled
twitter_data=csr_matrix((data, (row, col)), shape=(n_rows, n_features)).toarray()
twitter_target = np.array(twitter_target)

final n_row=[0 0 0 ... 0 0 0]


In [8]:
print("resulting matrix:")
print(twitter_data)

resulting matrix:
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [9]:
print(twitter_labels)

['Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy'

In [10]:
print(twitter_target)

[0 0 0 ... 1 1 1]


Write a program in the following cell that splits the data matrix in training and test set (by random selection) and predicts the class (Joy/Sadness) of the messages on the basis of the words. 
Consider the two possible models:
multivariate Bernoulli and multinomial Bernoulli.
Find the accuracy of the models and test is the observed differences are significant.

In [11]:
print(f"{len(twitter_data)} x {len(twitter_data[0])}")

11981 x 11288


### Preparazione
I dati vegnono separati in training set e test set

In [12]:
X_train, X_test, y_train, y_test = train_test_split(twitter_data, twitter_target, test_size=0.4, random_state=0)

### Multivariate Bernoulli model
Viene definito un modello naive Bayes multivariato, con i seguenti parametri:
* viene eseguita una correzione di Laplace con coefficiente $\alpha = 1$, equivalente ad aggiungere due tweet: uno contenente tutti gli elementi, uno non contenente nessun elemento
* è assunto un priore uniforme $P(Y=Joy)=P(Y=Sadness)=\frac{1}{2}$
* le etichette sono binarizzate con riferimento alla presenza/assenza di un elemento nel tweet: $\texttt{twitter\_data[i, j]} \ge 1 \iff \texttt{binarized(twitter\_data[i, j])} = 1$

In [13]:
mv_clf = BernoulliNB(alpha=1.0, binarize=0.0, class_prior=[0.5, 0.5])

Misura dell'accuratezza tramite cross-validation

In [14]:
mv_clf_scores = cross_val_score(mv_clf, twitter_data, twitter_target, cv=10)
print("%0.2f accuracy with a standard deviation of %0.2f" % (mv_clf_scores.mean(), mv_clf_scores.std()))

0.95 accuracy with a standard deviation of 0.01


### Multinomial Bernoulli model
Viene definito un modello naive Bayes multivariato, con i seguenti parametri:
* viene eseguita una correzione di Laplace con coefficiente $\alpha = 1$, equivalente ad aggiungere due tweet: uno contenente tutti gli elementi, uno non contenente nessun elemento
* è assunto un priore uniforme $P(Y=Joy)=P(Y=Sadness)=\frac{1}{2}$

In [15]:
mn_clf = MultinomialNB(alpha=1.0, class_prior=[0.5, 0.5])

Misura dell'accuratezza tramite cross-validation

In [16]:
mn_clf_scores = cross_val_score(mn_clf, twitter_data, twitter_target, cv=10)
print("%0.2f accuracy with a standard deviation of %0.2f" % (mn_clf_scores.mean(), mn_clf_scores.std()))

0.95 accuracy with a standard deviation of 0.01


### Paired t-test
L'esecuzione di un paired t-test in cross validation richiede un'implementazione ad-hoc.
Procedura ispirata al lavoro di Sebastian Raschka nella libreria [mlxtend](http://rasbt.github.io/mlxtend/).

In [17]:
mv_clf_scores = []
mn_clf_scores = []

kf = StratifiedKFold(n_splits=10)

for train_index, test_index in kf.split(twitter_data, twitter_target):
    X_train, X_test = twitter_data[train_index], twitter_data[test_index]
    y_train, y_test = twitter_target[train_index], twitter_target[test_index]

    mv_clf.fit(X_train, y_train)
    mn_clf.fit(X_train, y_train)

    mv_clf_scores.append(mv_clf.score(X_test, y_test))
    mn_clf_scores.append(mn_clf.score(X_test, y_test))

_, p_value = ttest_ind(mv_clf_scores, mn_clf_scores)
print(f"p-value = {p_value}")

p-value = 0.595425810389132


Non essendo il p-value inferiore a $\alpha = 0.05$, non posso rifiutare l'ipotesi nulla (i due modelli performano ugualmente)